repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Lint (and apply safe fixes)
      - id: ruff
        args: [--fix]
      # Fomrat
      - id: ruff-format

  - repo: local
    hooks:
      - id: dennis-errors
        name: dennis lint (errors only)
        language: system
        entry: dennis-cmd lint --errorsonly changedetectionio/translations/
        files: ^changedetectionio/translations/.*\.(po|pot)$
        pass_filenames: false
